name: cto-crud-db
services:
  db:
    image: mysql:8.0
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      cto_net:
        aliases: ["db"]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -uroot -p${DB_ROOT_PASSWORD} -h 127.0.0.1 --silent",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: always

volumes:
  db_data:
    external: true
    name: cto_db_data

networks:
  cto_net:
    external: true
    name: cto_net
