name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Copy env
        run: cp .env.example .env

      - name: Build images
        run: docker compose build

      - name: Start services
        run: docker compose up -d

      - name: Wait for bootstrap marker
        run: |
          set -e
          for i in $(seq 1 180); do
            if docker compose exec -T app sh -lc "test -f /var/www/html/laravel/.bootstrap_done"; then
              echo "Bootstrap completed."
              exit 0
            fi
            sleep 2
          done
          echo "Timeout waiting for bootstrap."
          docker compose logs --no-color
          exit 1

      - name: Run tests
        run: docker compose exec -T app php /var/www/html/laravel/artisan test -q

      - name: Optional lint (Pint)
        run: |
          set -e
          docker compose exec -T app sh -lc '[ -f vendor/bin/pint ] && vendor/bin/pint -v -- --test || echo "Pint not installed (skipping)"'

      - name: Compose logs on failure
        if: ${{ failure() }}
        run: docker compose logs --no-color
